package com.example.demo.repositories;


import com.example.demo.models.User;
import org.springframework.data.mongodb.repository.MongoRepository;
import org.springframework.data.mongodb.repository.Query;

import java.util.List;
import java.util.stream.Stream;

/**
 * If we use @Id in our entity class, then object_id will be replaced by mongodb (which is inserted by default by mongodb and it is unique for each document) and
 * then it will be a primary key. Since now we don't have any key as primary key
 * --> Primary key is generated by default from mongodb. Therefore kuch bhi bharo primary key ke datatype mai islie string bhar dia abhi to
 */
public interface UserRepositories extends MongoRepository<User, String> {

    public List<User> findByName(String name);

    // find all the people which have age greater than some given age
    // jpql, native sql

    @Query("{age : {$gte: ?0 }}")
    public List<User> findUserByAge(int age);

    @Query("{'name' : ?0 }")
    public Stream<User> findByUserName(String name);
}
